---
name: CICD
on:
  push:
    branches:
      - main
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from Git hub"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
